version: '3'
services:
  node:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mariadb
    links:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
      - sql-data:/var/lib/mysql
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  sql-data: {}
