version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3000:3500
    depends_on:
      - mariadb
    links:
      - mariadb
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
  frontend:
    build: ./frontend
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 3001:3000
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  mariadb:
    image: mariadb
    volumes:
      - sql-data:/var/lib/mysql
    ports:
      - 3380:3306
    env_file:
      - ./backend/.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  sql-data: {}
